sonar.organization=delgadotrueba
sonar.projectKey=DelgadoTrueba_com.delgadotrueba.template.js.lib
sonar.projectName=com.delgadotrueba.template.js.lib
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

# Paths
sonar.sources=src
sonar.tests=src

# Exclusions
sonar.exclusions=scripts/**,src/**/*.spec.*,src/**/*.test.*
sonar.coverage.exclusions=src/index.tsx

# Test
sonar.test.inclusions=src/**/*.spec.*,src/**/*.test.*
sonar.javascript.lcov.reportPaths=coverage/**/lcov.info

# Typescript
sonar.javascript.tsconfigPath=tsconfig.base.json,tsconfig.mjs.json,tsconfig.cjs.json
